import json
import re
from copy import deepcopy

import jsonref
from scalpl import Cut


def check_path(c_data, path):
    try:
        return path in c_data
    except Exception:
        return False


def check_path_keypaths(key_paths, path):
    return path in key_paths


def clean_path(p):
    return '.'.join([i for i in p.split('.') if i != ''])


def delete_section(c_data, path, func_args=None):
    if check_path(c_data, path):
        del c_data[path]
    return c_data


def deref(data):
    """
    Convert a benedict object or a dictionary with references to a regular dictionary by serializing and deserializing it.
    """
    try:
        return json.loads(json.dumps(data))
    except Exception as e:
        if e.args[0] == 'Object of type Cut is not JSON serializable':
            return deref_cut(data)
        else:
            raise e


def deref_cut(c_data):
    """
    Convert a Cut object to a regular dictionary by serializing and deserializing it.
    """
    if isinstance(c_data, list):
        return [json.loads(json.dumps(i.data)) for i in c_data]
    return json.loads(json.dumps(c_data.data))


def get_cut_data(data):
    if isinstance(data, list):
        return [Cut(deepcopy(i)) for i in data]
    return Cut(deepcopy(data))


def get_array_regex(path):
    """
    Converts a path with array indexes given as [*]/[n] to a regex pattern that matches and captures paths with any index.
    """
    re_pattern = re.escape(path)
    re_pattern = (
        '^' + re.sub(r'\\\[((n|\\\*)\d*?)\\\]', r'\[(\\d+)\]', re_pattern) + '$'
    )
    return re.compile(re_pattern)


def get_all_paths(data, current_path=''):
    if isinstance(data, Cut):
        data = data.data
    paths = [current_path] if current_path else []
    if isinstance(data, dict):
        for k, v in data.items():
            new_path = f'{current_path}.{k}' if current_path else k
            paths.extend(get_all_paths(v, new_path))
    elif isinstance(data, list):
        for i, v in enumerate(data):
            new_path = f'{current_path}[{i}]'
            paths.extend(get_all_paths(v, new_path))
    return set(paths)


def merge_all_of(schema):
    """
    Recursively merges 'allOf' lists into a single dictionary.
    """
    if not isinstance(schema, dict):
        return schema

    if 'allOf' in schema:
        all_of_list = schema.pop('allOf')
        for subschema in all_of_list:
            # Recursively merge the subschema first
            merged_sub = merge_all_of(subschema)
            # Update the base schema with subschema properties
            for key, value in merged_sub.items():
                if key == 'properties':
                    schema['properties'] = {**schema.get('properties', {}), **value}
                else:
                    schema[key] = value

    if 'properties' in schema:
        for k, v in schema['properties'].items():
            schema['properties'][k] = merge_all_of(v)

    if 'items' in schema:
        schema['items'] = merge_all_of(schema['items'])

    return schema


def resolve_schema(schema, remove_defs=False, resolve_allOf=False):
    """
    Resolves a JSON schema by replacing references and optionally merging 'allOf' lists and removing '$defs'.
    """
    schema = jsonref.replace_refs(schema, jsonschema=True, proxies=False)
    if remove_defs and '$defs' in schema:
        del schema['$defs']
    if resolve_allOf:
        schema = merge_all_of(deepcopy(schema))
    return json.loads(json.dumps(schema))


def clean_pydantic_jsonschema(section):
    """Recursively removes {'type': 'null'} from anyOf lists tha are generated by pydantic for optional fields."""
    if isinstance(section, dict):
        if 'anyOf' in section:
            anyOf = [
                i
                for i in section['anyOf']
                if i != {'type': 'null'} and i != {'type': None}
            ]
            if len(anyOf) == 1:
                return clean_pydantic_jsonschema(anyOf[0])
        return {k: clean_pydantic_jsonschema(v) for k, v in section.items()}
    elif isinstance(section, list):
        return [clean_pydantic_jsonschema(i) for i in section]
    return section
